project_id = "vaogzhwzucijiyvyglls"

[functions.mapbox-token]
verify_jwt = true

[functions.email-stats]
verify_jwt = false

[functions.process-pending-emails]
verify_jwt = false

[functions.tvd-sync-players]
verify_jwt = false

[functions.tvd-player-status]
verify_jwt = false

[functions.tvd-verify-sync-player]
verify_jwt = false